// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtqp2tiNoe21_liHG0jjJGM_pttaoGN-g',
    appId: '1:956635458417:web:72ce93c0e26d65305624d0',
    messagingSenderId: '956635458417',
    projectId: 'narresa-eeefb',
    authDomain: 'narresa-eeefb.firebaseapp.com',
    storageBucket: 'narresa-eeefb.firebasestorage.app',
    measurementId: 'G-SNHVM35W0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6az97E0pwUOqOV960wwPmykFxH-B0eI',
    appId: '1:956635458417:android:8cc2f173c1d00c525624d0',
    messagingSenderId: '956635458417',
    projectId: 'narresa-eeefb',
    storageBucket: 'narresa-eeefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5taBqjqkP2Vr_GpSnGjd2BAW1577jiuQ',
    appId: '1:956635458417:ios:e703f89834cb26765624d0',
    messagingSenderId: '956635458417',
    projectId: 'narresa-eeefb',
    storageBucket: 'narresa-eeefb.firebasestorage.app',
    iosBundleId: 'com.example.nareesMedical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5taBqjqkP2Vr_GpSnGjd2BAW1577jiuQ',
    appId: '1:956635458417:ios:e703f89834cb26765624d0',
    messagingSenderId: '956635458417',
    projectId: 'narresa-eeefb',
    storageBucket: 'narresa-eeefb.firebasestorage.app',
    iosBundleId: 'com.example.nareesMedical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtqp2tiNoe21_liHG0jjJGM_pttaoGN-g',
    appId: '1:956635458417:web:ae2434651b841d1d5624d0',
    messagingSenderId: '956635458417',
    projectId: 'narresa-eeefb',
    authDomain: 'narresa-eeefb.firebaseapp.com',
    storageBucket: 'narresa-eeefb.firebasestorage.app',
    measurementId: 'G-RGRYJZM4GP',
  );
}
